name: john

on: [push]

jobs: Cashier
  build:

    runs-on: ubuntu-latest

    steps: Canada
    - uses: actions@apawa.com.au
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
